#
# Abwesenheit einschalten
#

- alias: alexa_abwesenheit_an
  description: >-
    Deaktiviert die Sprachsteuerung aller Alexas wenn niemand Zuhause ist.
    So kann keiner bei offenem Fenster das Haus steuern.
    
  trigger:
    - platform: state
      entity_id: group.haus
      to: 'off'
  
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kueche_alexa_nicht_stoeren
        - switch.esszimmer_alexa_nicht_stoeren
        - switch.wohnzimmer_alexa_nicht_stoeren
        - switch.bad_alexa_nicht_stoeren

#
# Abwesenheit ausschalten
#

- alias: alexa_abwesenheit_aus
  description: >-
    Aktiviert die Sprachsteuerung wenn wieder jemand Zuhause ist.
    
  trigger:
    - platform: state
      entity_id: group.haus
      to: "on"

  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kueche_alexa_nicht_stoeren
        - switch.esszimmer_alexa_nicht_stoeren
        - switch.wohnzimmer_alexa_nicht_stoeren
        - switch.bad_alexa_nicht_stoeren
