#
# Ausschalten
#

- alias: dg_flur_licht_ausschalten
  trigger:
  - platform: state
    entity_id: binary_sensor.flur_bewegungsmelder_dg_decke_bewegung
    to: 'off'
      
  action:
  - entity_id: light.flur_licht_dg
    service: light.turn_off

#
# Einschalten
#

- alias: dg_flur_licht_einschalten
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.flur_bewegungsmelder_dg_decke_bewegung
    to: 'on'
    for: 
    
  - platform: state
    entity_id: binary_sensor.flur_bewegungsmelder_treppe
    to: 'on'

  condition:
    condition: template
    value_template: "{{ state_attr('sun.sun', 'elevation') < 3 }}"

  action:
  - entity_id: light.flur_licht_dg
    service: light.turn_on