#
# Morgens unter der Woche
#

- alias: weihnachtsbeleuchtung_einschalten_morgens
  description: >-
    Schaltet die Weihnachtsbeleuchtung 45 MInuten vor Sonnenaufgang ein.
    Aber nur Wochentags.
  
  trigger:
  - platform: time
    at: "06:30:00"
  
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

  action:
  - service: light.turn_on
    entity_id: light.garten_licht_weihnachten

#
# Abends
#

- alias: weihnachtsbeleuchtung_einschalten_abends
  description: >-
    Schaltet die Weihnachsbeleuchtung ein, wenn die Sonne untergeht.

  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 3
    
  condition:
    condition: time
    after: "15:00:00"
    before: "21:00:00"

  action:
  - service: light.turn_on
    entity_id: light.garten_licht_weihnachten
  - service: notify.wohnzimmer_firetv
    data:
      title: "Weihnachtsbeleuchtung"
      message: "Die Sonne geht unter. Die Weihnachtsbeleuchtung wird eingeschalten."
      data:
        timeout: 25
        file:
          url: "https://d368g9lw5ileu7.cloudfront.net/races/races-35xxx/35908/raceBanner-3ntEeaK7-bxDbE7.jpg"
