###############
# Abwesenheit # 
###############

## Abwesenheit einschalten ##

- alias: alexa_abwesenheit_an
  description: >-
    Deaktiviert die Sprachsteuerung aller Alexas wenn niemand Zuhause ist.
    So kann keiner bei offenem Fenster das Haus steuern.
  
trigger:
    - platform: state
      entity_id: group.haus
      to: 'off'

  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kueche_alexa_nicht_stoeren
        - switch.esszimmer_alexa_nicht_stoeren
        - switch.wohnzimmer_alexa_nicht_stoeren
        - switch.bad_alexa_nicht_stoeren

## Abwesenheit ausschalten ##

- alias: alexa_abwesenheit_aus
  description: >-
    Aktiviert die Sprachsteuerung wenn wieder jemand Zuhause ist.
    
  trigger:
    - platform: state
      entity_id: group.haus
      to: "on"

  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kueche_alexa_nicht_stoeren
        - switch.esszimmer_alexa_nicht_stoeren
        - switch.wohnzimmer_alexa_nicht_stoeren
        - switch.bad_alexa_nicht_stoeren

#######################
# Einschaltlautstärke #
#######################

- alias: alexa_einschaltlautstaerke
  description: >-
    Setzt automatisch die Lautstärke aller Alexas auf ein bestimmtes Level.
    So wird vermieden dass Alexa zu laut beginnt, wenn beim letzten mal lauter gehört wurde.
    
  trigger:
    - platform: state
      entity_id: 
        - media_player.kueche_alexa
        - media_player.esszimmer_alexa
        - media_player.wohnzimmer_alexa
        - media_player.bad_alexa
      to: "paused"
      for: "00:15:00" 
    - platform: state
      entity_id: 
        - media_player.kueche_alexa
        - media_player.esszimmer_alexa
        - media_player.wohnzimmer_alexa
        - media_player.bad_alexa
      to: "standby"
  
  condition: []
  
  action:
    - service: media_player.volume_set
      data: 
        entity_id: "{{ trigger.entity_id }}"
        volume_level: 0.33
